server:
  port: 8090
  servlet:
    context-path: /bcsRegression
    
spring:
  datasource:
    #url: jdbc:mysql://10.20.59.204:3306/text_mail?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&user=dbuser&password=Db@123!
    url: jdbc:db2://10.20.38.55:60000/CXLDB
    username: db2user
    password: db2ibmuser
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.ibm.db2.jcc.DB2Driver
  # redis相关配置
  redis:
    database: 0
    host: ranchertest
    port: 30663
    password: redis
    # 连接超时时间 单位 ms（毫秒）
    timeout: 3000
    pool:
    # 连接池中的最大空闲连接，默认值也是8。
    max-idle: 8
    #连接池中的最小空闲连接，默认值也是0。
    min-idle: 0
    # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
    max-active: 8
    # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
    max-wait: -1


  config:
    activate:
      on-profile: develop